# GROWI Export

;GROWI_URL       = https://<user name>.growi.cloud
;GROWI_PATH      = /user/<user name>
;ACCESS_TOKEN    = <your access token here>
;EXPORT_DIR      = ./growi_export (default)
;NORMALIZATION_FORM = NFC (default) | NFD | raw

GROWI_URL       = https://63rabbits.growi.cloud
;GROWI_PATH      = /user/63rabbits/Contents/ZZ.遊び場
GROWI_PATH      = /user/63rabbits
ACCESS_TOKEN    = f4ca4a924ca7e6766df9c95e97bd4efa0d983b9a14131c8cb4f797354deb972b
EXPORT_DIR      = ./aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
