# GROWI Export

;GROWI_URL       = https://<user name>.growi.cloud
;GROWI_PATH      = /user/<user name>
;ACCESS_TOKEN    = <your access token here>
;EXPORT_DIR      = ./growi_export (default)
;NORMALIZATION_FORM = NFC (default) | NFD | raw
